---
# this works for single nodes but I have no idea why
- name: Setup /etc/hosts with node ip
  lineinfile:
   path: /etc/hosts
   regexp: '^[0-9\.]+[ \t]+(.*{{ ansible_hostname }}.*)'
   # ansible_default_ipv4.address will be undefined without a route to the internet
   # as it happens on my lan
   line: '{{ ansible_default_ipv4.address }} \1'
   # previously used workaround
   # line: "{{ hostvars[inventory_hostname]['ansible_' + iface]['ipv4']['address'] }}"
   backrefs: yes
   state: present
   backup: true
  when: ansible_virtualization_type != "docker"
