---
- name: Install gnupg
  apt:
   name:
     - gnupg
   state: present
   update_cache: yes
  when: ansible_distribution == 'Debian'

- name: Setup /etc/hosts req by Proxmox 3,4,5.
  include_tasks: hosts.yml
  when:
    - ansible_distribution == 'Debian'

- name: Include overrides specific to Debian 7.
  include_tasks: pve3.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "7"

- name: Include overrides specific to Debian 8.
  include_tasks: pve4.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "8"

- name: Include overrides specific to Debian 9.
  include_tasks: pve5.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "9"

- name: Include overrides specific to Debian 10.
  include_tasks: pve6.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_major_version == "10"

- name: Run common post install tasks.
  include_tasks: postpve.yml
  when:
    - ansible_distribution == 'Debian'