---
- name: Remove os-prober
  apt:
   name: os-prober
   state: absent
  notify: update-grub

- name: Remove PVE enterprise repo file
  file:
   path: /etc/apt/sources.list.d/pve-enterprise.list
   state: absent
  notify: update-grub

- name: Update repositories cache without enterprise repo
  apt:
   update_cache: yes
  notify: update-grub
