---
- name: Remove os-prober
  ansible.builtin.apt:
   name: os-prober
   state: absent
  notify: "Update-grub"

- name: Remove PVE enterprise repo file
  ansible.builtin.file:
   path: /etc/apt/sources.list.d/pve-enterprise.list
   state: absent
  notify: "Update-grub"

- name: Update repositories cache without enterprise repo
  ansible.builtin.apt:
   update_cache: yes
  notify: "Update-grub"
