---
- name: Add pve apt repo
  ansible.builtin.apt_repository:
   repo: deb [arch=amd64] http://download.proxmox.com/debian {{ ansible_distribution_release }} pve-no-subscription
   state: present
   filename: pve-install-repo

- name: Add the Proxmox Apt signing key
  ansible.builtin.apt_key:
   url: 'http://download.proxmox.com/debian/key.asc'
   state: present

- name: Update repositories cache and run apt-get upgrade
  ansible.builtin.apt:
   update_cache: yes
   upgrade: dist

- name: Install the pve kernel
  ansible.builtin.apt:
   name:
    - pve-firmware
    - pve-kernel-2.6.32-26-pve

- name: Install proxmox packages
  ansible.builtin.apt:
   name:
    - proxmox-ve-2.6.32
    - ntp
    - ssh
    - lvm2
    - postfix
    - ksm-control-daemon
    - vzprocps
    - open-iscsi
    - bootlogd
  when: ansible_virtualization_type != "docker"
