---
# add apt repository
# use ansible_distribution_release instead of hard-coding wheezy,jessie,stretch
- apt_repository:
    repo: deb [arch=amd64] http://download.proxmox.com/debian {{ ansible_distribution_release }} pve-no-subscription
    state: present
    filename: pve-install-repo

- name: Add the Proxmox Apt signing key
  apt_key:
    url: 'http://download.proxmox.com/debian/key.asc'
    state: present

- name: Update repositories cache and run apt-get upgrade
  apt:
    update_cache: yes
    upgrade: dist

- name: Install the pve kernel
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - pve-firmware
    - pve-kernel-2.6.32-26-pve
# the pve3 kernel is 2.6 instead of 3.2
# I don't know how to remove the running kernel atm
#- name: Remove the debian kernel
#  apt:
#    name: "{{ packages }}"
#    state: absent
#  vars:
#    packages:
#    - linux-image-amd64
#    - linux-image-3.2.0-4-amd64
#    - linux-image-3.2.0-6-amd64
#    - linux-image-3.2.0-5-amd64
- name: Install proxmox packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - proxmox-ve-2.6.32
    - ntp
    - ssh
    - lvm2
    - postfix
    - ksm-control-daemon
    - vzprocps
    - open-iscsi
    - bootlogd
  when: ansible_virtualization_type != "docker"

