---
- name: Add pve apt repo
  ansible.builtin.apt_repository:
   repo: deb [arch=amd64] http://download.proxmox.com/debian {{ ansible_distribution_release }} pve-no-subscription
   state: present
   filename: pve-install-repo

- name: Add the Proxmox Apt signing key
  ansible.builtin.apt_key:
   url: 'http://download.proxmox.com/debian/key.asc'
   state: present

- name: Update repositories cache and run apt-get upgrade
  ansible.builtin.apt:
   update_cache: yes
   upgrade: dist

- name: Install proxmox packages
  ansible.builtin.apt:
   name:
    - proxmox-ve
    - ssh
    - postfix
    - ksm-control-daemon
    - open-iscsi
    - systemd-sysv
  when: ansible_virtualization_type != "docker"
