---
- name: Create apt src list file for D9
  template:
   src: pve-install-repo-stretch.j2
   dest: /etc/apt/sources.list.d/pve-install-repo.list
   owner: root
   group: root
   mode: 0644
   backup: yes

- name: Add proxmox's apt key
  apt_key:
   url: 'http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg'
   state: present


- name: Update repositories cache and run apt-get upgrade
  apt:
   update_cache: yes
   upgrade: dist

- name: Install proxmox packages
  apt:
   name:
    - proxmox-ve
    - postfix
    - open-iscsi
  when: ansible_virtualization_type != "docker"
