---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-qwe1/docker-debian:10-nonfree-molecule}"
    privileged: true
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    memory: 1024
    cpu: 1
provisioner:
  name: ansible
  log: true
scenario:
  name: default
