---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: "${MOLECULE_DISTRO:-debian:9}"
    pull: yes
    memory: 4096
    cpu: 2
    groups:
      - proxmox

provisioner:
  name: ansible
  log: true
  inventory:
    group_vars:
      proxmox:
        user: qwe
        username: qwe
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
